name: "Bump Modpack Metadata"
description: "Change a modpack's version to a specified tag"

inputs:
  version:
    description: "The version to bump the modpack to, without the 'v' prefix"
    required: true

  modpack:
    description: "Path to the modpack directory"
    required: false
    default: "."

  pack-file:
    description: "Path to the pack config file"
    required: false
    default: "pack.toml"

  branch:
    description: "Branch, where to do the bump"
    required: false
    default: "main"

runs:
  using: "composite"

  steps:
    - name: Check Out Git Repository
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.branch }}

    - name: Install nix
      uses: cachix/install-nix-action@v22

    - name: Set the Version in ${{ inputs.pack-file }}
      run: sed -i 's/version = "[^"]*"/version = "${{ inputs.version }}"/' ${{ inputs.modpack }}/${{ inputs.pack-file }}
      shell: bash

    - name: Packwiz refresh
      run: |
        set -e
        nix develop --command packwiz refresh
      shell: bash
      working-directory: ${{ inputs.modpack }}

    - name: Push The Updated Version
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "chore(${{ inputs.modpack }}): bump version to ${{ inputs.version }}"
