name: Release

on:
  push:
    branches:
      - main

env:
  default-release-modrinth: 'true'
  default-release-curseforge: 'false'


jobs:

  parse-current-modpacks:
    uses: ./.github/workflows/get-modpacks-list.yml

  release-please:
    name: Handle Releases
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    needs:
      - parse-current-modpacks
    if: ${{ (needs.parse-current-modpacks.outputs.modpack-folders) != '[]' }}

    strategy:
      fail-fast: false
      matrix:
        modpack: ${{ fromJson(needs.parse-current-modpacks.outputs.modpack-folders) }}

    defaults:
      run:
        working-directory: ${{ matrix.modpack }}

    steps:      
      - name: Perform Release with Release Please
        id: release-please
        uses: google-github-actions/release-please-action@v3
        with:
          monorepo-tags: true
          path: ${{ matrix.modpack }}
          release-type: simple
          package-name: ${{ matrix.modpack }}
          prerelease: true
          changelog-types: > 
            [{"type":"feat","section":"★ Features","hidden":false},
            {"type":"fix","section":"♻ Bug Fixes","hidden":false},
            {"type":"mod","section":"☀ Modpack Changes","hidden":false},
            {"type":"update","section":"⚘ Modpack Updates","hidden":false},
            {"type":"chore","section":"⛭ Miscellaneous","hidden":true}]


      - name: Parse tag from PR title
        uses: actions-ecosystem/action-regex-match@v2
        id: version
        with:
          text: ${{ fromJson(steps.release-please.outputs.pr).title }}
          regex: '(?<=\s)(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?$'
        if: ${{ steps.release-please.outputs.pr != '' }}


      - name: Check Out Git Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0


      - name: Bump Version
        uses: ./.github/actions/bump-modpack-metadata
        with:
          version: ${{ steps.version.outputs.match }}
          modpack: ${{ matrix.modpack }}
          branch: ${{ fromJson(steps.release-please.outputs.pr).headBranchName }}
        if: ${{ steps.version.outputs.match != '' }}


      - name: Get Latest tag
        id: tag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        if: ${{ steps.release-please.outputs.releases_created }}

      - name: Parse Pack File
        id: parse
        uses: ./.github/actions/parse
        with:
          modpack: ${{ matrix.modpack }}
        if: ${{ steps.release-please.outputs.releases_created }}

      - name: Set Mod Vendors
        id: set-mod-vendors
        run: |
          [[ ! -z "${{ secrets.CURSEFORGE_TOKEN }}" && ! -z "${{ secrets.CURSEFORGE_ID }}" ]] && echo "curseforge=true" >> $GITHUB_OUTPUT || echo "curseforge=false" >> $GITHUB_OUTPUT
          [[ ! -z "${{ secrets.MODRINTH_TOKEN }}" && ! -z "${{ secrets.MODRINTH_ID }}" ]] && echo "modrinth=true" >> $GITHUB_OUTPUT || echo "modrinth=false" >> $GITHUB_OUTPUT
        shell: bash
        if: ${{ steps.release-please.outputs.releases_created }}

      - name: Build Modpack
        uses: ./.github/actions/build
        with:
          modpack: ${{ matrix.modpack }}
          artifact-name: ${{ matrix.modpack }}
          build-modrinth: ${{ env.default-release-modrinth }}
          build-curse: ${{ env.default-release-curseforge }}
        if: ${{ steps.release-please.outputs.releases_created }}

      - name: Upload Modpack to GitHub Releases
        uses: ./.github/actions/release-github
        with:
          artifact-name: ${{ matrix.modpack }}
          release-tag: ${{ steps.tag.outputs.tag }}
        if: ${{ steps.release-please.outputs.releases_created }}

      # --- Release
      - name: Release Modpack to Vendors
        uses: ./.github/actions/release
        with:
          modpack: ${{ matrix.modpack }}
          release-tag: ${{ steps.tag.outputs.tag }}
          loader: ${{ steps.parse.outputs.loader }}
          game-version: ${{ steps.parse.outputs.game-version }}
          upload-modrinth: ${{ steps.set-mod-vendors.outputs.modrinth }}
          upload-curse: ${{ steps.set-mod-vendors.outputs.curseforge }}
          MODRINTH_ID: ${{ secrets.MODRINTH_ID }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          CURSEFORGE_ID: ${{ secrets.CURSEFORGE_ID }}
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
        if: |
          steps.release-please.outputs.releases_created &&
          (steps.set-mod-vendors.outputs.modrinth || steps.set-mod-vendors.outputs.curseforge)
